import { ArrowUpRight, ExternalLink, Mail, MapPin } from "lucide-react";

export default function Contact() {
  return (
    <section id="contact" className="relative overflow-hidden bg-[var(--cobalt)] py-20 text-white sm:py-28">
      <div className="absolute -right-20 -top-20 size-96 rounded-full border-[70px] border-white/10" /><div className="absolute -bottom-36 left-1/3 size-80 rounded-full bg-[var(--accent)] opacity-20 blur-3xl" />
      <div className="shell relative"><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-[11px] font-bold uppercase tracking-widest"><span className="size-2 rounded-full bg-[var(--accent)]" />06 / Let&apos;s connect</div><h2 className="display mt-8">GOT AN IDEA?<br /><span className="text-[var(--accent)]">LET&apos;S MAKE IT REAL.</span></h2><div className="mt-14 grid gap-3 md:grid-cols-3"><a className="group flex min-h-40 items-end justify-between rounded-[1.75rem] bg-white p-5 text-black transition-transform hover:-translate-y-1" href="mailto:virgiatharaditya37@gmail.com"><span><Mail size={21} /><span className="mt-8 block text-[10px] font-bold uppercase tracking-widest text-black/45">Email</span><span className="mt-1 block text-sm font-bold sm:text-base">virgiatharaditya37@gmail.com</span></span><ArrowUpRight className="transition-transform group-hover:rotate-12" /></a><a className="group flex min-h-40 items-end justify-between rounded-[1.75rem] bg-black p-5 text-white transition-transform hover:-translate-y-1" href="https://linkedin.com/in/virgi-atha-raditya" target="_blank" rel="noreferrer"><span><ExternalLink size={21} /><span className="mt-8 block text-[10px] font-bold uppercase tracking-widest text-white/45">LinkedIn</span><span className="mt-1 block font-bold">virgi-atha-raditya</span></span><ArrowUpRight className="transition-transform group-hover:rotate-12" /></a><div className="flex min-h-40 items-end rounded-[1.75rem] bg-[var(--accent)] p-5 text-black"><span><MapPin size={21} /><span className="mt-8 block text-[10px] font-bold uppercase tracking-widest text-black/45">Based in</span><span className="mt-1 block font-bold">Banjarbaru, South Kalimantan<br />Indonesia</span></span></div></div></div>
    </section>
  );
}
